spring:
  session:
    store-type: jdbc
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      repositories:
        enabled: false
    jdbc:
      repositories:
        enabled: true
    jpa:
      repositories:
        enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

pos:
  service:
    cache-type: local
